---
- name: install redis
  hosts: all
  user: root
  roles:
    - { role: redis/redissrvs,  redis_cluster_replicas: 0, redis_node_list: "{{ groups['all'] | map('extract', hostvars, ['ansible_eth0', 'ipv4', 'address']) | arraypermute( [':'] ) | arraypermute( [6379,6380] ) }}" }
  vars:
    - redis_port:
      - 6379
      - 6380