---
# tasks file for redis
- name: remove /root/test-ansible/redis
  file: path={{ redis_dir }} owner=root group=root mode=0655 state=absent
- name: remove /root/test-ansible/redis/6379/config
  file: path={{ redis_dir }}/{{ item.port }}/{{ item.type }} owner=root group=root mode=0655 state=directory
  with_items:
    - { port: 6379, type: "config"}
    - { port: 6379, type: "logs"}
    - { port: 6379, type: "data"}
    - { port: 6380, type: "config"}
    - { port: 6380, type: "logs"}
    - { port: 6380, type: "data"}
- name: get redis package
  get_url: url=http://download.redis.io/releases/redis-{{ version }}.tar.gz dest=/root/test-ansible/redis-{{ version }}.tar.gz
- name: Untar redis files
  unarchive: src=/root/test-ansible/redis-{{ version }}.tar.gz dest=/root/test-ansible copy=no
- name: make install
  shell: cd /root/test-ansible/redis-{{ version }} && make && cd /root/test-ansible/redis-{{ version }}/src && make PREFIX=../../ install
- name: Create the cluster node redis.conf
  template:
    src: "redis.conf.j2"
    dest: "{{ redis_dir }}/{{ item }}/config/redis_{{ item }}.conf"
  with_items:
    - 6379
    - 6380
- name: Create the cluster node redis.service
  template:
    src: "redis.service.j2"
    dest: "/etc/init.d/redis_{{ item }}"
  with_items:
    - 6379
    - 6380
- name: change mode
  shell: chmod 755 /etc/init.d/redis_{{ item }}
  with_items:
    - 6379
    - 6380
- name: install sysv-rc-conf
  apt: name=sysv-rc-conf state=latest
#- name: change mode
#  shell: chkconfig --add redis_{{ item }}
#  with_items:
#    - 6379
#    - 6380
