---
# tasks file for redis
- name: Ensure /root/test-ansible/redis/{{ redis_port }}/logs exists
  file: path=/root/test-ansible/redis owner=root group=root mode=0655 state=absent
- name: Ensure /root/test-ansible/redis/{{ redis_port }}/logs exists
  file: path=/root/test-ansible/redis/{{ redis_port }}/logs owner=root group=root mode=0655 state=directory
- name: Ensure /root/test-ansible/redis/{{ redis_port }}/data exists
  file: path=/root/test-ansible/redis/{{ redis_port }}/data owner=root group=root mode=0655 state=directory
- name: Ensure /root/test-ansible/redis/{{ redis_port }}/config exists
  file: path=/root/test-ansible/redis/{{ redis_port }}/config owner=root group=root mode=0655 state=directory
- name: get redis package
  get_url: url=http://download.redis.io/releases/redis-{{ version }}.tar.gz dest=/root/redis-{{ version }}.tar.gz