---
# tasks file for redis

# make a clean environment
- name: kill all redis process
  shell: ps -ef | grep redis | awk '{print $2}' | xargs kill -9
  ignore_errors: True
- name: remove /root/test-ansible/redis
  file: path={{ redis_dir }} owner=root group=root mode=0655 state=absent
- name: mkdir for redis - config,logs,data
  file: path={{ redis_dir }}/{{ item.port }}/{{ item.type }} owner=root group=root mode=0655 state=directory
  with_items:
    - { port: 6379, type: "config"}
    - { port: 6379, type: "logs"}
    - { port: 6379, type: "data"}
    - { port: 6380, type: "config"}
    - { port: 6380, type: "logs"}
    - { port: 6380, type: "data"}
- name: get redis package
  get_url: url=http://download.redis.io/releases/redis-{{ version }}.tar.gz dest={{ redis_dir }}/redis-{{ version }}.tar.gz
- name: Untar redis files
  unarchive: src={{ redis_dir }}/redis-{{ version }}.tar.gz dest={{ redis_dir }} copy=no
- name: make install
  shell: cd {{ redis_install_dir }} && make && cd {{ redis_install_src_dir }} && make PREFIX=../../ install
- name: copy redis-trib.rb
  shell: cp {{ redis_install_src_dir }}/redis-trib.rb {{ redis_bin_dir }}
- name: Create the cluster node redis.conf
  template:
    src: "redis.conf.j2"
    dest: "{{ redis_dir }}/{{ item }}/config/redis_{{ item }}.conf"
  with_items:
    - 6379
    - 6380
- name: Create the cluster node redis.service1
  template:
    src: "redis.service.j2"
    dest: "/etc/init.d/redis_{{ item }}.service"
  with_items:
    - 6379
    - 6380
- name: Create the cluster node redis.service2
  template:
    src: "redis.service.j2"
    dest: "/etc/init.d/redis_{{ item }}"
  with_items:
    - 6379
    - 6380
- name: change mode1
  shell: chmod 755 /etc/init.d/redis_{{ item }}.service
  with_items:
    - 6379
    - 6380
- name: change mode2
  shell: chmod 755 /etc/init.d/redis_{{ item }}
  with_items:
    - 6379
    - 6380
- name: install sysv-rc-conf
  apt: name=sysv-rc-conf state=latest
- name: config service
  shell: sysv-rc-conf redis_{{ item }} on && systemctl daemon-reload
  with_items:
    - 6379
    - 6380
- name: start and enable the redis node.
  service:
    name: redis_{{ item }}
    state: restarted
    enabled: yes
    force: true
  with_items:
    - 6379
    - 6380
- name: install ruby
  apt: name=ruby state=latest
- name: install rubygems
  apt: name=rubygems state=latest
- name: gem install redis
  shell: gem install redis
- name: Create initialization script
  template: src=initialize_cluster.j2 dest={{ redis_bin_dir }}/initialize_cluster.sh
- name: Initialize cluster
  shell: bash {{ redis_bin_dir }}/initialize_cluster.sh
  run_once: true
