---
# tasks file for redis
- name: remove /root/test-ansible/redis
  file: path={{ redis_dir }} owner=root group=root mode=0655 state=absent
- name: remove /root/test-ansible/redis/6379/config
  file: path={{ redis_dir }}/{{ item.port }}/{{ item.type }} owner=root group=root mode=0655 state=directory
  with_items:
    - { port: 6379, type: "config"}
    - { port: 6379, type: "logs"}
    - { port: 6379, type: "data"}
    - { port: 6380, type: "config"}
    - { port: 6380, type: "logs"}
    - { port: 6380, type: "data"}
- name: get redis package
  get_url: url=http://download.redis.io/releases/redis-{{ version }}.tar.gz dest=/root/test-ansible/redis-{{ version }}.tar.gz
- name: Untar redis files
  unarchive: src=/root/test-ansible/redis-{{ version }}.tar.gz dest=/root/test-ansible copy=no
- name: make install
  shell: cd /root/test-ansible/redis-{{ version }} && make && cd /root/test-ansible/redis-{{ version }}/src && make PREFIX=../../ install
- name: Create the cluster node redis.conf
  template:
    src: "redis.conf.j2"
    dest: "{{ redis_dir }}/{{ item }}/config/redis_{{ item }}.conf"
  with_items:
    - 6379
    - 6380
- name: Create the cluster node redis.service1
  template:
    src: "redis.service.j2"
    dest: "/etc/init.d/redis_{{ item }}.service"
  with_items:
    - 6379
    - 6380
- name: Create the cluster node redis.service2
  template:
    src: "redis.service.j2"
    dest: "/etc/init.d/redis_{{ item }}"
  with_items:
    - 6379
    - 6380
- name: change mode1
  shell: chmod 755 /etc/init.d/redis_{{ item }}.service
  with_items:
    - 6379
    - 6380
- name: change mode2
  shell: chmod 755 /etc/init.d/redis_{{ item }}
  with_items:
    - 6379
    - 6380
- name: install sysv-rc-conf
  apt: name=sysv-rc-conf state=latest
- name: config service
  shell: sysv-rc-conf redis_{{ item }} on && systemctl daemon-reload
  with_items:
    - 6379
    - 6380
- name: start and enable the redis node.
  service:
    name: redis_{{ item }}
    state: restarted
    enabled: yes
    force: true
  with_items:
    - 6379
    - 6380
- name: install ruby
  apt: name=ruby state=latest
- name: install rubygems
  apt: name=rubygems state=latest
- name: gem install redis
  shell: gem install redis
- name: Create initialization script
  template: src=initialize_cluster.j2 dest={{ redis_bin_dir }}/initialize_cluster.sh
- name: Initialize cluster
  shell: bash {{ redis_bin_dir }}/initialize_cluster.sh

#- name: print node list
#  debug:
#    msg: "{{ ansible_ssh_host }}"
#- name: print node redis_node_list

#  debug:
#    msg: "{{ item }}"
#  with_items:
#    - "{{ redis_node_list }}"
#- name: print node redis_node_list2
#  debug:
#    msg: "{{ item }}"
#  with_items:
#    - 6379
#    - 6380