---
# tasks file for redis
- name: remove /root/test-ansible/redis
  file: path=/root/test-ansible/redis owner=root group=root mode=0655 state=absent
- name: make directories
  shell: mkdir -p /root/test-ansible/redis/6379/{config,data,logs} && mkdir -p /root/test-ansible/redis/6380/{config,data,logs}
- name: get redis package
  get_url: url=http://download.redis.io/releases/redis-{{ version }}.tar.gz dest=/root/test-ansible/redis-{{ version }}.tar.gz
- name: Untar redis files
  unarchive: src=/root/test-ansible/redis-{{ version }}.tar.gz dest=/root/test-ansible copy=no
- name: make install
  shell: cd /root/test-ansible/redis-{{ version }} && make && cd /root/test-ansible/redis-{{ version }}/src && make PREFIX=../../ install
