---
# tasks file for redis

# set ruby cluster by ruby script
- name: install ruby
  apt: name=ruby state=latest
- name: install rubygems
  apt: name=rubygems state=latest
- name: gem install redis
  shell: gem install redis
- name: Create initialization script
  template: src=initialize_cluster.j2 dest={{ redis_bin_dir }}/initialize_cluster.sh
- name: Initialize cluster
  shell: bash {{ redis_bin_dir }}/initialize_cluster.sh
  run_once: true
  ignore_errors: True
